services:
  # VirtuAI Office Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: virtuai-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/virtuai_office.db
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_METAL=0
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - virtuai-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: virtuai-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - virtuai-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: virtuai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - virtuai-network

volumes:
  ollama_data:
    driver: local
  backend_data:
    driver: local

networks:
  virtuai-network:
    driver: bridge
